
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { SpeedInsights } from "@vercel/speed-insights/next"
const inter = Inter({ subsets: ["latin"] });
import { GoogleAnalytics } from '@next/third-parties/google'
import { Navbar } from "./components/Navbar";
import { Analytics } from "@vercel/analytics/react"


export const metadata: Metadata = {
  title: "Sai Surya's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="bg-gray-900 text-yellow-50">
        <main className="flex min-h-screen flex-col items-center container mx-auto bg-gray-900">
          <div className="mb-12">
            <Navbar />
          </div>
          <div className="w-full">{children}</div>
          <Analytics />
        </main>

      </body>
      <SpeedInsights />
      <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || "G-XYZ"} />
    </html>
  );
}
